spring: 
  profiles: 
    active: 
    - dev

---

spring: 
  profiles: dev
  application:
    name: victor-springcloud-config-dev
---
spring: 
  profiles: test 
  application: 
    name: victor-springcloud-config-test